// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://memyfenhtjjnozosdqts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lbXlmZW5odGpqbm96b3NkcXRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyODg1OTYsImV4cCI6MjA2MDg2NDU5Nn0.GiQPTKNG_EujedoWjzifdXJkyrUOaqOBUC8i770PP9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);